### ISSUE TITLE
@nuxtjs/pwa module update required

### ISSUE THREAD

**Issue by umbrellait-evgeny-zhukov** [wagerfield/nuxt-stack#537]
I'm seeing a critical issue with PWA icons, which is related to the https://github.com/nuxt-community/pwa-module/issues/231

Please, actualize dependencies 🙏

**Comment by z0lo13** [comment]
@wagerfield Are you going to update it? Without it the project is pretty unusable

**Comment by umbrellait-evgeny-zhukov** [comment]
@wagerfield as I can see, the @renovate-bot already updated all the dependencies, so all that needed is publish a new release to the NPM registry. This issue could be closed, BTW.

**Comment by wagerfield** [comment]
@umbrellait-evgeny-zhukov @z0lo13 0.8.1 published. Sorry for the delay, not got a lot of time to maintain my OS projects at the moment.
